### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by woiwoz** [SunstriderEmu/BugTracker#3919]
crash logs:

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./worldserver'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  Trinity::AbortHandler (sigval=<optimized out>)
    at /home/243server/sunstrider/src/common/Debugging/Errors.cpp:178
178         Crash(formattedMessage.c_str());
[Current thread is 1 (Thread 0x7fb5977fe700 (LWP 29018))]
(gdb) bt
#0  Trinity::AbortHandler (sigval=<optimized out>)
    at /home/243server/sunstrider/src/common/Debugging/Errors.cpp:178
#1  <signal handler called>
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#3  0x00007fb801aeb535 in __GI_abort () at abort.c:79
#4  0x00007fb801ed6983 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fb801edc8c6 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fb801edc901 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007fb801edcb34 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007fb801ed88b7 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007fb801f04f1a in std::random_device::_M_init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x0000556ac042e985 in std::random_device::random_device (__token="default",
    this=0x7fb5977fc200) at /usr/include/c++/8/bits/random.h:1573
#11 SFMTRand::SFMTRand (this=0x7fb568002680)
    at /home/243server/sunstrider/src/common/Utilities/SFMTRand.cpp:28
#12 0x0000556ac042dd8d in GetRng ()
    at /home/243server/sunstrider/src/common/Utilities/Random.cpp:16
#13 0x0000556ac042e065 in rand32 ()
    at /home/243server/sunstrider/src/common/Utilities/Random.cpp:61
#14 RandomEngine::operator() (this=<optimized out>)
    at /home/243server/sunstrider/src/common/Utilities/Random.h:75
#15 std::generate_canonical<float, 24ul, RandomEngine> (__urng=...)
    at /usr/include/c++/8/bits/random.tcc:3333
#16 std::__detail::_Adaptor<RandomEngine, float>::operator() (this=<synthetic pointer>)
    at /usr/include/c++/8/bits/random.h:181
#17 std::uniform_real_distribution<float>::operator()<RandomEngine> (this=<synthetic pointer>,
    __urng=..., __p=<synthetic pointer>...) at /usr/include/c++/8/bits/random.h:1823
#18 std::uniform_real_distribution<float>::operator()<RandomEngine> (__urng=...,
    this=<synthetic pointer>) at /usr/include/c++/8/bits/random.h:1814
#19 frand (min=min@entry=0, max=max@entry=1)
    at /home/243server/sunstrider/src/common/Utilities/Random.cpp:48
#20 0x0000556ac011efb1 in RandomMovementGenerator<Creature>::SetRandomLocation (
    this=0x7fb6ee38a2d0, owner=0x7fb6ee386c00)
    at /home/243server/sunstrider/src/server/game/Movement/MovementGenerators/RandomMovementGenerator.cpp:75
#21 0x0000556ac011f7d8 in RandomMovementGenerator<Creature>::DoUpdate (diff=<optimized out>,
    owner=<optimized out>, this=<optimized out>)
    at /home/243server/sunstrider/src/server/game/Entities/Unit/Unit.h:1206
#22 MovementGeneratorMedium<Creature, RandomMovementGenerator<Creature> >::Update (
    this=<optimized out>, owner=<optimized out>, time_diff=<optimized out>)
    at /home/243server/sunstrider/src/server/game/Movement/MovementGenerator.h:107
#23 0x0000556ac01005dc in MotionMaster::Update (this=0x7fb6ee3897c0, diff=diff@entry=50)
    at /home/243server/sunstrider/src/server/game/Movement/MotionMaster.cpp:262
#24 0x0000556abff58462 in Unit::Update (this=this@entry=0x7fb6ee386c00,
    objectDiff=objectDiff@entry=47, mapDiff=mapDiff@entry=50)
--Type <RET> for more, q to quit, c to continue without paging--
   er/game/Entities/Unit/Unit.cpp:456
#25 0x0000556abfe3f78e in Creature::Update (this=0x7fb6ee386c00, objectDiff=47, mapDiff=50)
    at /home/243server/sunstrider/src/server/game/Entities/Creature/Creature.cpp:769

#26 0x0000556abfe82422 in WorldObject::UpdateHelper::UpdateRealTime (
    this=this@entry=0x7fb5977fdaa0, map=<optimized out>, now=54315175, mapDiff=<optimized out>)
    at /home/243server/sunstrider/src/server/game/Entities/Object/Object.cpp:760
#27 0x0000556ac00bb8f3 in Trinity::ObjectUpdater::Visit (m=..., this=0x7fb5977fdb20)
    at /home/243server/sunstrider/src/server/game/Grids/Notifiers/GridNotifiersImpl.h:40
#28 VisitorHelper<Trinity::ObjectUpdater, Creature> (c=..., v=...)
    at /home/243server/sunstrider/src/server/shared/Dynamic/TypeContainerVisitor.h:28
#29 VisitorHelper<Trinity::ObjectUpdater, Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > (c=..., v=...)
    at /home/243server/sunstrider/src/server/shared/Dynamic/TypeContainerVisitor.h:34
#30 VisitorHelper<Trinity::ObjectUpdater, GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > (c=..., v=...)
    at /home/243server/sunstrider/src/server/shared/Dynamic/TypeContainerVisitor.h:35
#31 VisitorHelper<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (c=..., v=...)
    at /home/243server/sunstrider/src/server/shared/Dynamic/TypeContainerVisitor.h:41
#32 TypeContainerVisitor<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > >::Visit (this=0x7fb5977fdb10,
    c=...) at /home/243server/sunstrider/src/server/shared/Dynamic/TypeContainerVisitor.h:75
#33 Grid<Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::Visit<Trinity::ObjectUpdater> (visitor=..., this=0x7fb6edf12ef8)
    at /home/243server/sunstrider/src/server/game/Grids/Grid.h:72
#34 NGrid<8u, Player, TypeList<Player, TypeList<Creature, TypeList<Corpse, TypeList<DynamicObject, TypeNull> > > >, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > >::VisitGrid<Trinity::ObjectUpdater, TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > (visitor=..., y=0, x=1, this=<optimized out>)
    at /home/243server/sunstrider/src/server/game/Grids/NGrid.h:156
#35 Map::Visit<Trinity::ObjectUpdater, TypeMapContainer<TypeList<GameObject, TypeList<Creature, TypeList<DynamicObject, TypeList<Corpse, TypeNull> > > > > > (visitor=..., cell=...,
    this=0x556aeba07300) at /home/243server/sunstrider/src/server/game/Maps/Map.h:951
#36 Map::VisitNearbyCellsOf (worldVisitor=..., gridVisitor=..., obj=<optimized out>,
    this=0x556aeba07300) at /home/243server/sunstrider/src/server/game/Maps/Map.cpp:872
#37 Map::VisitNearbyCellsOf (this=0x556aeba07300, obj=<optimized out>, gridVisitor=...,
    worldVisitor=...) at /home/243server/sunstrider/src/server/game/Maps/Map.cpp:849
#38 0x0000556ac00bbdca in Map::UpdateCells (this=0x556aeba07300, mapDiff=<optimized out>)
    at /home/243server/sunstrider/src/server/game/Maps/Map.cpp:1042
#39 0x0000556ac00bf14f in Map::Update (this=0x556aeba07300, mapDiff=50)
    at /home/243server/sunstrider/src/server/game/Maps/Map.cpp:1106
#40 0x0000556ac00a8713 in Map::DoUpdate (this=this@entry=0x556aeba07300, maxDiff=50,
    minimumTimeSinceLastUpdate=50) at /home/243server/sunstrider/src/server/game/Maps/Map.cpp:905
#41 0x0000556ac00e9255 in MapUpdateRequest::call (this=0x7fb568000e30)
    at /home/243server/sunstrider/src/server/game/World/World.h:817
#42 MapUpdater::OnceWorkerThread (this=0x556ac09cbca0 <MapManager::instance()::instance+160>)
    at /home/243server/sunstrider/src/server/game/Maps/MapUpdater.cpp:188
--Type <RET> for more, q to quit, c to continue without paging--
#43 0x00007fb801f05b2f in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#44 0x00007fb801c93fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#45 0x00007fb801bc24cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by woiwoz** [comment]
Core was generated by `./worldserver'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  Trinity::AbortHandler (sigval=<optimized out>)
    at /home/243server/sunstrider/src/common/Debugging/Errors.cpp:178
178         Crash(formattedMessage.c_str());
[Current thread is 1 (Thread 0x7f0773fff700 (LWP 30963))]
(gdb) bt
#0  Trinity::AbortHandler (sigval=<optimized out>)
    at /home/243server/sunstrider/src/common/Debugging/Errors.cpp:178
#1  <signal handler called>
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#3  0x00007f099e93a535 in __GI_abort () at abort.c:79
#4  0x00007f099ed25983 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f099ed2b8c6 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f099ed2b901 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f099ed2bb34 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007f099ed278b7 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00007f099ed53f1a in std::random_device::_M_init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x0000562081db2985 in std::random_device::random_device (__token="default",
    this=0x7f0773ffd190) at /usr/include/c++/8/bits/random.h:1573
#11 SFMTRand::SFMTRand (this=0x7f07680027c0)
    at /home/243server/sunstrider/src/common/Utilities/SFMTRand.cpp:28
#12 0x0000562081db1d8d in GetRng ()
    at /home/243server/sunstrider/src/common/Utilities/Random.cpp:16
#13 0x0000562081db1ed9 in rand32 ()
    at /home/243server/sunstrider/src/common/Utilities/Random.cpp:61
#14 RandomEngine::operator() (this=<optimized out>)
    at /home/243server/sunstrider/src/common/Utilities/Random.h:75
#15 std::generate_canonical<double, 53ul, RandomEngine> (__urng=...)
    at /usr/include/c++/8/bits/random.tcc:3333
#16 0x0000562081db21d9 in std::__detail::_Adaptor<RandomEngine, double>::operator() (
    this=<synthetic pointer>) at /usr/include/c++/8/bits/random.h:1818
#17 std::uniform_real_distribution<double>::operator()<RandomEngine> (this=<synthetic pointer>,
    __urng=..., __p=<synthetic pointer>...) at /usr/include/c++/8/bits/random.h:1823
#18 std::uniform_real_distribution<double>::operator()<RandomEngine> (__urng=...,
    this=<synthetic pointer>) at /usr/include/c++/8/bits/random.h:1814
#19 rand_chance () at /home/243server/sunstrider/src/common/Utilities/Random.cpp:73
#20 0x0000562081bbc608 in roll_chance_f (chance=<optimized out>)
    at /home/243server/sunstrider/src/common/Utilities/Random.h:56
#21 Spell::DoEffectOnLaunchTarget (this=this@entry=0x7f0768001e80, targetInfo=...,
--Type <RET> for more, q to quit, c to continue without paging--
    multiplier=multiplier@entry=1, effIndex=effIndex@entry=0 '\000')
    at /home/243server/sunstrider/src/server/game/Spells/Spell.cpp:8441
#22 0x0000562081bbc915 in Spell::HandleLaunchPhase (this=0x7f0768001e80)
    at /home/243server/sunstrider/src/server/game/Spells/Spell.cpp:8359
#23 0x0000562081bce411 in Spell::_cast (this=0x7f0768001e80, skipCheck=<optimized out>)
    at /home/243server/sunstrider/src/server/game/Spells/Spell.cpp:3907
#24 0x0000562081bcf547 in SpellEvent::Execute (this=0x7f07680013a0, e_time=2198145,
    p_time=<optimized out>) at /home/243server/sunstrider/src/server/game/Spells/Spell.cpp:8219
#25 0x0000562081db1b7d in EventProcessor::Update (this=this@entry=0x5620c9b63df0,
    p_time=p_time@entry=50) at /usr/include/c++/8/bits/stl_multimap.h:549
#26 0x00005620818dc38c in Unit::Update (this=this@entry=0x5620c9b63cc0,
    objectDiff=objectDiff@entry=50, mapDiff=mapDiff@entry=50)
    at /home/243server/sunstrider/src/server/game/Entities/Unit/Unit.cpp:418
#27 0x0000562081892826 in Player::Update (this=0x5620c9b63cc0, objectDiff=50, mapDiff=50)
    at /home/243server/sunstrider/src/server/game/Entities/Player/Player.cpp:1215
#28 0x0000562081806422 in WorldObject::UpdateHelper::UpdateRealTime (
    this=this@entry=0x7f0773ffeb28, map=map@entry=0x5620afbcbe50, now=now@entry=2264920,
    mapDiff=mapDiff@entry=50)
    at /home/243server/sunstrider/src/server/game/Entities/Object/Object.cpp:760
#29 0x0000562081a2bb13 in Map::UpdatePlayers (this=0x5620afbcbe50)
    at /home/243server/sunstrider/src/server/game/Maps/Map.cpp:973
#30 0x0000562081a430a1 in Map::Update (this=0x5620afbcbe50, mapDiff=50)
    at /home/243server/sunstrider/src/server/game/Maps/Map.cpp:1098
#31 0x0000562081a2c713 in Map::DoUpdate (this=this@entry=0x5620afbcbe50, maxDiff=50,
    minimumTimeSinceLastUpdate=50) at /home/243server/sunstrider/src/server/game/Maps/Map.cpp:905
#32 0x0000562081a6d255 in MapUpdateRequest::call (this=0x7f07a815ab60)
    at /home/243server/sunstrider/src/server/game/World/World.h:817
#33 MapUpdater::OnceWorkerThread (this=0x56208234fca0 <MapManager::instance()::instance+160>)
    at /home/243server/sunstrider/src/server/game/Maps/MapUpdater.cpp:188
#34 0x00007f099ed54b2f in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#35 0x00007f099eae2fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#36 0x00007f099ea114cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)
